### PR TITLE
RC

### PR DESCRIPTION
**Pull request by worlds6440**
Been upgrading RC module alongside main Launcher.

Launcher now handles RC mode with button A for RC and B for NONE. Calibrated classic joystick values for both left and right sticks and have been getting sensible results back on shell prompts for motor speeds.

Launcher now gracefully handles RC thread on exit so no threads left running.

Core module upgraded to test Arduino module value and will not call it if its set to None. This means its safe to leave in code (in case we want to revive it) but we can add our GPIO stuff in place and potentially flick switch between them if needs be.

Should be safe to merge back with master as it's more working than whats currently there.

### CODE REVIEW

**Review by PKM-UK — COMMENTED** [review]
I'm not a fan of big commented-out blocks of code like in rc.py - could this be factored out into a function which we either call or don't call as necessary? Other than that this looks fine, the option to not have an Arduino connected is a helpful change.

**Comment by worlds6440** [comment]
Yup, that code was purely for calibration so can easily be moved into sub-method and not called. Will try and do that at lunch.

**Comment by brianwiddas** [comment]
Looks good to me. I like the "don't call the arduino if it's not there" option; I was trying to work out how to incorporate the GPIO motor control into the code, and that makes it a lot easier.

**Comment by worlds6440** [comment]
Updated code, will close this pull request and submit new.

**Pull request closed without merging**
