### PR TITLE
Update how we display messages

### PR DESCRIPTION
**Pull request by robberwick**
This PR is a roll-up of #8 and #9, and also amends the `show_message` function so that it can display both title and message as required. This function is now name as `set_display_contents` to better reflect that, and is use throughout `launcher.py`.

### CODE REVIEW

**Comment by robberwick** [comment]
@worlds6440 Was your concern here that this would affect the use of `show_motor_config` and `show_aux_1_config` in `Calibration.py`? If so, I think it should be ok, as both of those methods continue to exist with unchanged signatures and just proxy through to the updated `set_display_contents` internally.

**Comment by worlds6440** [comment]
Rob, I'll close this for now as the code has moved on significantly and a few of the re-written methods have been phased out. However, I will take on-board the comments as they are all gold.

**Comment by robberwick** [comment]
@worlds6440 Sure. Apologies for not realising that there was work underway to address it. I did check the list of outstanding issues, and didn't see anything there pertaining to the Launcher, so assumed there wasn't. A good workflow is to ensure that there's always an issue raised to track any feature, in order to give it both visibility, and a place to discuss approaches etc. :+1: 

FWIW, your replacement PR looks good to me ;-)

**Comment by worlds6440** [comment]
Yup, apologies. We're still learning GIT so it's nice to have someone like you guiding us towards best practice. Hopefully we will be testing RC mode on the bot tonight!

**Pull request closed without merging**
